### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bigosm** [kamildyla/bottles#1]
```java
    public static void main(String[] args) {
```
* Keep array of bottles instead of `numberOfBottles`.
* You can have for example `Int numberOfBottles() { return this.bottles.count }` to have easier access to some repeatable operations.
```java
        int numOfBottles = 0;
```
* I would advise to use `boolean` properties with `is`, `has` or similar prefix.
here you can read something more: https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig
* Second advise on this property is to use it as method. `boolean hasAnyBottles() { return this.bottles.count > 0 }`
```java
        boolean flagNumOfBottles = true;

        Scanner sc = new Scanner(System.in);

        do {
            System.out.print("Podaj ilość butelek: ");
            numOfBottles = sc.nextInt();
            if (numOfBottles < 0) {
                flagNumOfBottles = false;
                System.out.println("Podano nieprawidłową ilość");
            }
            else {
                flagNumOfBottles = true;
            }
        }
        while (!flagNumOfBottles);
```
* Creating new bottles in separate function
```java
        // random capacity and fill level of bottles
        Bottle[] bottle = new Bottle[numOfBottles];
        for (int i = 0; i < numOfBottles; i++) {
            bottle[i] = new Bottle(Bottle.randomCapacity());
            bottle[i].randomFillLevel(bottle[i].getCapacity()) ;
            System.out.println("Butelka nr " + bottle[i].getId() + ", pojemność: " + bottle[i].getCapacity() + " l, Napełniono: " + bottle[i].getFillLevel() + " l");
        }

        System.out.println("\nCo chcesz zrobić: \n1. Nalej\n2. Wylej \n3. Przelej \n4. Zakończ");

        int choiceOperation = sc.nextInt();

        /* to add:
         * choice operation in switch:case
         * exceptions for inputs
         * body oof rest of methods
         */

    }
```

**Comment by kamildyla** [comment]
- `int numOfBottles` is getting from customer, so if I create an array of bottles, I should create other `int` to keep the value from customer. Please advise.
- `boolean flagNumOfBottles = true;`  corrected at `boolean isNumOfBottlesRight = true;`
- method `createFillBottle()` created

**Comment by bigosm** [comment]
>     * `int numOfBottles` is getting from customer, so if I create an array of bottles, I should create other `int` to keep the value from customer. Please advise.
Okay this is my mistake. I didn't notice that `int numOfBottles = 0;` this was a property in function :) In this circumstances, this property was fine.
>     * `boolean flagNumOfBottles = true;`  corrected at `boolean isNumOfBottlesRight = true;`
But I still see field to improve this part of program to be more readable.

```java
        int numOfBottles = 0;
        do {
            try {
                System.out.print("Enter number of bottles: ");
                Scanner sc = new Scanner(System.in);
                numOfBottles = sc.nextInt();
            }
            catch (InputMismatchException e) {
                System.out.println("Invalid quantity specified");
            }
            boolean isValid = numberOfBottles > 0 // `numberOfBottles > 0` is already a `flag` no need to create another one and explicitly say `true` or `false`.
            if (!isValid) { System.out.println("Invalid quantity specified"); }
        }
        while(!isValid);
```

>     * method `createFillBottle()` created
That is much better.

#### What to do next?
- As your program will grow and you will add more functionalities, it will be hard to keep all of that code in one `main` function. Instead you could try to split business logic and UI to separate classes. Standard MVC pattern would fit in here.
- Also it is much easier to make "Code Review" in **Pull Request** (And it should happen before merging to master :))

**Comment by kamildyla** [comment]
This part of code is awsome:

```
 int numOfBottles = 0;
 do {
     try {
         System.out.print("Enter number of bottles: ");
         Scanner sc = new Scanner(System.in);
         numOfBottles = sc.nextInt();
     }
     catch (InputMismatchException e) {}
     isValid = numOfBottles > 0;
     if (!isValid) {
         System.out.println("Invalid quantity specified");
     }
 }
 while (!isValid);
```

Thanks ;)
